In [10]:
import pandas as pd
import numpy as np

train = pd.read_csv("../../data/optiver_volatility/train.csv")
test = pd.read_csv("../../data/optiver_volatility/test.csv")

print(train.shape)
print(train.head())
print(test.head())

(428932, 3)
   stock_id  time_id    target
0         0        5  0.004136
1         0       11  0.001445
2         0       16  0.002168
3         0       31  0.002195
4         0       62  0.001747
   stock_id  time_id row_id
0         0        4    0-4
1         0       32   0-32
2         0       34   0-34

In [13]:
book = pd.read_parquet(
    "../../data/optiver_volatility/book_train.parquet/stock_id=0"
)

trade = pd.read_parquet(
    "../../data/optiver_volatility/trade_train.parquet/stock_id=0"
)

trade.head()

   time_id  seconds_in_bucket     price  size  order_count
0        5                 21  1.002301   326           12
1        5                 46  1.002778   128            4
2        5                 50  1.002818    55            1
3        5                 57  1.003155   121            5
4        5                 68  1.003646     4            1

In [14]:
stock_id = 0
time_id = 5

book = pd.read_parquet(
    f"../../data/optiver_volatility/book_train.parquet/stock_id={stock_id}"
)

trade = pd.read_parquet(
    f"../../data/optiver_volatility/trade_train.parquet/stock_id={stock_id}"
)

target = train.loc[
    (train["stock_id"] == stock_id) &
    (train["time_id"] == time_id),
    "target"
].iloc[0]

print(f"stock_id = {stock_id}")
print(f"time_id  = {time_id}")
print(f"target   = {target}")

print("\nBOOK DATA")
display(book[book["time_id"] == time_id])

print("\nTRADE DATA")
display(trade[trade["time_id"] == time_id])

stock_id = 0
time_id  = 5
target   = 0.004135767

BOOK DATA

,time_id,seconds_in_bucket,bid_price1,ask_price1,bid_price2,ask_price2,bid_size1,ask_size1,bid_size2,ask_size2
0,5,0,1.001422,1.002301,1.001370,1.002353,3,226,2,100
1,5,1,1.001422,1.002301,1.001370,1.002353,3,100,2,100
2,5,5,1.001422,1.002301,1.001370,1.002405,3,100,2,100
3,5,6,1.001422,1.002301,1.001370,1.002405,3,126,2,100
4,5,7,1.001422,1.002301,1.001370,1.002405,3,126,2,100
...,...,...,...,...,...,...,...,...,...,...
297,5,585,1.003129,1.003749,1.003025,1.003801,100,3,26,3
298,5,586,1.003129,1.003749,1.002612,1.003801,100,3,2,3
299,5,587,1.003129,1.003749,1.003025,1.003801,100,3,26,3
300,5,588,1.003129,1.003749,1.002612,1.003801,100,3,2,3
301,5,593,1.003129,1.003749,1.003025,1.003801,100,3,26,3

TRADE DATA

    time_id  seconds_in_bucket     price  size  order_count
0         5                 21  1.002301   326           12
1         5                 46  1.002778   128            4
2         5                 50  1.002818    55            1
3         5                 57  1.003155   121            5
4         5                 68  1.003646     4            1
5         5                 78  1.003762   134            5
6         5                122  1.004207   102            3
7         5                127  1.004577     1            1
8         5                144  1.004370     6            1
9         5                147  1.003964   233            4
10        5                177  1.003853     1            1
11        5                183  1.003956     2            1
12        5                187  1.004267   165            2
13        5                207  1.003543    72            4
14        5                218  1.004155    33            5
15        5                254  1.003905   100            1
16        5                263  1.003905     1            1
17        5                265  1.004111     2            2
18        5                278  1.004370   106            2
19        5                331  1.004680     3            2
20        5                366  1.004215     6            2
21        5                380  1.004116   432            9
22        5                389  1.004422     1            1
23        5                398  1.004215   100            1
24        5                430  1.003853     2            1
25        5                435  1.003905     1            1
26        5                464  1.003749     2            1
27        5                470  1.003465   200            7
28        5                471  1.003646   101            2
29        5                488  1.003905     2            1
30        5                514  1.004012    29            3
31        5                523  1.004008     1            1
32        5                540  1.003543     4            1
33        5                549  1.003129     2            1
34        5                550  1.002799    13            3
35        5                551  1.002561   154            5
36        5                562  1.002715     1            1
37        5                572  1.003191   499            6
38        5                581  1.003478     8            3
39        5                585  1.003646    26            2

In [15]:
stock_id = 0
time_id = 4

book_test = pd.read_parquet(
    f"../../data/optiver_volatility/book_test.parquet/stock_id={stock_id}"
)

trade_test = pd.read_parquet(
    f"../../data/optiver_volatility/trade_test.parquet/stock_id={stock_id}"
)

print(f"stock_id = {stock_id}")
print(f"time_id  = {time_id}")

print("\nBOOK DATA")
display(book_test[book_test["time_id"] == time_id])

print("\nTRADE DATA")
display(trade_test[trade_test["time_id"] == time_id])

stock_id = 0
time_id  = 4

BOOK DATA

,time_id,seconds_in_bucket,bid_price1,ask_price1,bid_price2,ask_price2,bid_size1,ask_size1,bid_size2,ask_size2
0,4,0,1.000049,1.000590,0.999656,1.000639,91,100,100,24
1,4,1,1.000049,1.000590,0.999656,1.000639,91,100,100,20
2,4,5,1.000049,1.000639,0.999656,1.000885,290,20,101,15

TRADE DATA

   time_id  seconds_in_bucket     price  size  order_count
0        4                  7  1.000344     1            1
1        4                 24  1.000049   100            7
2        4                 27  1.000059   100            3